version: '3.8'

services:
  # Keycloak service
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev --import-realm --hostname localhost --http-port 8081
    env_file:
      - ./configs/keycloak.env
    volumes:
      - ./configs/keycloak:/opt/keycloak/data/import
    ports:
      - 8081:8081
      - 9000:9000
    networks:
      - backend
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'exec 3<>/dev/tcp/localhost/8081; echo -e "GET /health/ready HTTP/1.1\nhost: localhost:8080\n" >&3; timeout --preserve-status 1 cat <&3 | grep -m 1 status | grep -m 1 UP; ERROR=$?; exec 3<&-; exec 3>&-; exit $ERROR'
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 2g
          cpus: "1.0"
        reservations:
          memory: 1g
          cpus: "0.5"

  # Consul service
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    restart: always
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - consul_data:/consul/data
    ports:
      - "8500:8500"
    command: agent -dev -ui -bind=0.0.0.0 -client=0.0.0.0
    depends_on:
      - keycloak
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
        reservations:
          memory: 512m
          cpus: "0.25"


  subscription-service:
    image: openjdk:21
    volumes:
      - ./backend_services/subscriptionService/build/libs/subscriptionService-1.0.0.jar:/app/service.jar
    command: ["java", "-jar", "/app/service.jar"]
    depends_on:
      - consul
      - api-gateway
    env_file:
      - ./configs/subscription_service.env
    networks:
      - backend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
        reservations:
          memory: 512m
          cpus: "0.25"

  user-service:
    image: openjdk:21
    volumes:
      - ./backend_services/userService/build/libs/userService-1.0.0.jar:/app/service.jar
    command: ["java", "-jar", "/app/service.jar"]
    depends_on:
      - consul
      - api-gateway
    env_file:
      - ./configs/user_service.env
    networks:
      - backend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
        reservations:
          memory: 512m
          cpus: "0.25"

  engagement-service:
    image: openjdk:21
    container_name: engagement-service
    volumes:
      - ./backend_services/engagementService/build/libs/engagementService-1.0.0.jar:/app/service.jar
    command: ["java", "-jar", "/app/service.jar"]
    depends_on:
      - consul
      - api-gateway
    env_file:
      - ./configs/engagement_service.env
    networks:
      - backend

  api-gateway:
    image: openjdk:21
    container_name: api-gateway
    volumes:
      - ./api_gateway/build/libs/api_gateway-1.0.0.jar:/app/service.jar
    command: ["java", "-jar", "/app/service.jar"]
    depends_on:
      keycloak:
        condition: service_healthy
      consul:
        condition: service_started
    env_file:
      - ./configs/gateway.env
    ports:
      - 8080:8080
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
        reservations:
          memory: 512m
          cpus: "0.25"
      restart_policy:
        condition: on-failure

  post-service:
    image: openjdk:21
    volumes:
      - ./backend_services/postService/build/libs/postService-1.0.0.jar:/app/service.jar
    command: ["java", "-jar", "/app/service.jar"]
    depends_on:
      - consul
      - api-gateway
    env_file:
      - ./configs/post_service.env
    networks:
      - backend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1g
          cpus: "0.75"
        reservations:
          memory: 512m
          cpus: "0.25"



  media-service:
    image: openjdk:21
    volumes:
      - ./backend_services/mediaService/build/libs/mediaService-1.0.0.jar:/app/service.jar
    command: [ "java", "-jar", "/app/service.jar" ]
    depends_on:
      - consul
      - api-gateway
    env_file:
      - ./configs/media_service.env
    networks:
      - backend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 2g
          cpus: "1.0"
        reservations:
          memory: 1g
          cpus: "0.5"

  creator-service:
    image: openjdk:21
    volumes:
      - ./backend_services/creatorService/build/libs/creatorService-1.0.0.jar:/app/service.jar
    command: [ "java", "-jar", "/app/service.jar" ]
    depends_on:
      - consul
      - api-gateway
    env_file:
      - ./configs/creator_service.env
    networks:
      - backend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
        reservations:
          memory: 512m
          cpus: "0.25"

  frontend:
    build:
      context: ./frontend/onlypans-frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend/onlypans-frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - ./configs/frontend.env
    depends_on:
      - api-gateway
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  consul_data: